lrdpv2: Set default value of --svm option to an empty string
A default value of "svm" causes the following error to be seen:

linux-ramdump-parser-v2\extensions\hyp_trace.py", line 43, in determine_kaslr
    hyp_kaslr_addr = hyp_kaslr_addr + self.page_offset
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

Change-Id: I9434c4528e891be6a0e3993e671c27f3ed46157d