lrdp: ftrace_event_list: fix the bug that event_name_by_type not defined
This is used in linux-ramdump-parser-v2/parsers/ftrace.py:322:
event_name = fevent_list.event_name_by_type.get(etype)

but missed the define.

error log:

----------begin FtraceParser----------
Wrote ftrace buffer size info to ftrace_buffer_info.txt
failed to _dump_enabled_ftrace_events: 'FtraceParser_Event_List' object
has no attribute 'event_name_by_type'
Total pages across cpu trace buffers = 90355 for global

Change-Id: Ia876919864b682a5e2664a65f3a1ab38e433ee05